---
- hosts: server
  become: true
  become_user: root
  vars:
    nginx:
      target_root_path: sample
      hostname: www
      domain: hoge.com
      location_path: /home/nginx
  roles:
    - {role: node, node_var: 4.4.5}
    - {role: nginx, conf_template: static-site}
  tasks:
    - name: Install rsync
      pacman: name=rsync state=present
    - name: Copy target dir
      synchronize:
        src={{nginx.target_root_path | mandatory}}/{{nginx.hostname | mandatory}}.{{nginx.domain | mandatory}}/
        dest=/home/nginx/{{nginx.hostname | mandatory}}.{{nginx.domain | mandatory}}/
