---
- name: Upgrade packages
  pacman: update_cache=yes upgrade=yes

- name: Install MariaDB
  pacman: name=mariadb state=present
# - name: MariaDB init
#   command: mysql_install_db --user=mysql --basedir=/usr --datadir=/var/lib/mysql
- name: Start mysqld.service
  service: name=mysqld state=restarted
