---
- name: Upgrade packages
  pacman: update_cache=yes upgrade=yes
- name: Install NodeJS and npm
  pacman: name=nodejs,npm
- name: Install n in global
  npm: name=n global=yes
- name: Downgrade NodeJS
  command: n {{node_var}}
