---
- name: Upgrade packages
  pacman: update_cache=yes upgrade=yes

- name: Install Git
  pacman: name=git state=present

- name: Install jdk8
  pacman: name=jdk8-openjdk state=present
- name: Set jdk8
  command: archlinux-java set java-8-openjdk
- name: Clone sbt-play project
  git:
    repo={{repo_name}}
    clone=yes
    dest=/home/root/sbt-play
    ssh_opts="-o StrictHostKeyChecking=no"
  when: repo_name is defined

- name: "Create /etc/systemd/service/"
  file: path=/etc/systemd/service/ state=directory
- name: Create playapp.service
  template:
    src=roles/sbt-play/templates/playapp.service
    dest=/etc/systemd/service/playapp.service
- name: Start app:{{app_name}}
  service: name=playapp state=restarted
